name: KeniUtils
version: '1.1'
main: org.keni.keniutils.KeniUtils
api-version: '${project.version}'
commands:
  info:
    description: Get info about server
    usage: /info
  kreload:
    description: reloading plugin
    usage: /kreload
    permission: keniutils.reload
  msg:
    description: msg
    usage: /msg <player> <message>
    aliases: [pm, tellp]
    permission: "msg.use"
    tab-completer: org.keni.keniutils.commands.msg
  sit:
    description: Sit
    usage: /sit
  dimention:
    description: "Changes your privacy status (private/public)"
    usage: "/dimention <private/public>"
    tab-completer: org.keni.keniutils.commands.dimentions
permissions:
  keniutils.reload:
    description: reloading plugin
    default: op
overrides:
  msg: keniutils:msg